In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
from statsmodels.stats.stattools import durbin_watson
import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

import os
os.chdir(r"C:\Users\willi\OneDrive\Documents\Woolf Institute Data Analytics\Module 5 Time Series Analysis\04 Live Data Sets")

In [3]:
# Read in the data
mktmix = pd.read_csv("mktmix.csv")
print("✅ Dataset Loaded Successfully")
print(mktmix.head())

✅ Dataset Loaded Successfully
   Time period  Sales  Base_Price  Radio  InStore          TV
0            1  19564   15.029276  245.0   15.452  101.780000
1            2  19387   15.029276  314.0   16.388   76.734000
2            3  23889   14.585093  324.0   62.692  131.590200
3            4  20055   15.332887  298.0   16.573  119.627060
4            5  20064   15.642632  279.0   41.504  103.438118


In [6]:
#Formula
formula = 'Sales ~ Base_Price + Radio  + InStore + TV'

In [7]:
model = smf.ols(formula, data=mktmix).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.648
Model:                            OLS   Adj. R-squared:                  0.633
Method:                 Least Squares   F-statistic:                     43.65
Date:                Sat, 14 Jun 2025   Prob (F-statistic):           9.64e-21
Time:                        09:21:56   Log-Likelihood:                -825.76
No. Observations:                 100   AIC:                             1662.
Df Residuals:                      95   BIC:                             1675.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   4.757e+04   3019.360     15.756      0.000    4.16e+04    5.36e+04
Base_Price -1952.5944    191.249    -10.210      0.000   -2332.271   -1572.918
Radio          1.1928      1.109      1.076      0.285      -1.008       3.394
InStore       35.0531      7.323      4.787      0.000      20.515      49.591
TV             7.4444      2.217      3.357      0.001       3.042      11.847
==============================================================================
Omnibus:                        3.728   Durbin-Watson:                   0.898
Prob(Omnibus):                  0.155   Jarque-Bera (JB):                3.098
Skew:                          -0.332   Prob(JB):                        0.212
Kurtosis:                       3.551   Cond. No.                     9.63e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.63e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [12]:
#Calculate the Durbin-Watson statistic to test for autocorrelation in the residuals of the model.
dw_test = durbin_watson(model.resid)
print(f"Durbin-Watson statistic: {dw_test:.2f}")

Durbin-Watson statistic: 0.90


### Parameter Estimation - Maximum Likelihood Estimation Method

In [23]:
# Assuming Data contains your exogenous variables in the DataFrame format
exog_data = mktmix[['Base_Price', 'Radio', 'InStore', 'TV']]

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler to your data and transform it
scaled_exog_data = scaler.fit_transform(exog_data)

# Convert the scaled data back to a DataFrame (if needed)
scaled_exog_df = pd.DataFrame(scaled_exog_data, columns=exog_data.columns, index=exog_data.index)
print(scaled_exog_df)

     Base_Price     Radio   InStore        TV
0     -0.527145 -0.135053 -1.282738 -0.917822
1     -0.527145  0.662095 -1.213998 -1.503800
2     -1.371031  0.777623  2.186549 -0.220381
3      0.049676  0.477249 -1.200412 -0.500271
4      0.638150  0.257744  0.630511 -0.879029
..          ...       ...       ...       ...
99     1.238511  0.407932 -0.252160 -1.623646
100    0.638150       NaN  1.152446 -0.138419
101    1.238511       NaN -0.264057  0.841048
102    0.638150       NaN  1.323120  0.550220
103    1.851001       NaN  0.973107  0.494088

[104 rows x 4 columns]


In [21]:
# Assuming Data contains your exogenous variables in the DataFrame format
exog_data = mktmix[['Base_Price', 'Radio', 'InStore', 'TV']]

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler to your data and transform it
scaled_exog_data = scaler.fit_transform(exog_data)

print(scaled_exog_data)

[[-0.52714457 -0.13505299 -1.28273795 -0.91782201]
 [-0.52714457  0.66209469 -1.21399848 -1.50379964]
 [-1.37103081  0.77762334  2.18654939 -0.22038088]
 [ 0.04967631  0.47724885 -1.20041215 -0.50027118]
 [ 0.63814973  0.25774442  0.63051086 -0.87902859]
 [ 0.34244186  0.02668712 -0.91906499 -0.2949854 ]
 [ 0.93682955 -0.25058164 -0.03242853 -1.08439186]
 [ 0.34244186  0.38482593 -1.1971808  -0.50890271]
 [-0.52714457  0.67364756  0.87227407 -0.42305533]
 [ 0.34244186  0.70830615 -0.41468172  1.08647679]
 [ 0.93682955  0.73141188 -1.01820847  0.59273198]
 [ 1.23851112  0.84694053  0.28637283  0.93756345]
 [ 0.93682955  1.02023351 -0.3076802   0.82155787]
 [ 1.23851112  0.24619155 -1.62570095  0.15950792]
 [ 1.23851112 -0.07728867 -0.43766832  0.18034795]
 [ 0.93682955 -0.07728867 -0.07208592 -0.25231006]
 [-0.52714457 -0.07728867 -0.49135268 -0.31168534]
 [ 0.34244186  0.1306629  -0.53115695 -0.59972237]
 [-1.09254362  0.35016734 -0.21764324 -0.43556172]
 [-0.24017618  0.38482593 -1.55

In [35]:
scaled_exog_df.isnull().sum()


Base_Price    0
Radio         4
InStore       0
TV            0
dtype: int64

In [37]:
len(mktmix['Sales']), len(scaled_exog_df)


(100, 100)

In [36]:
scaled_exog_df = scaled_exog_df.dropna()
mktmix = mktmix.loc[scaled_exog_df.index]  # Align target variable too


In [38]:
# Fit a SARIMAX model to the sales data with exogenous variables.
model = sm.tsa.SARIMAX(mktmix['Sales'], exog=scaled_exog_df, order=(0, 0, 0), trend='c',error_ar = 1)

results = model.fit()

results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                               SARIMAX Results                                
==============================================================================
Dep. Variable:                  Sales   No. Observations:                  100
Model:                        SARIMAX   Log Likelihood                -825.766
Date:                Sat, 14 Jun 2025   AIC                           1663.532
Time:                        09:59:08   BIC                           1679.163
Sample:                             0   HQIC                          1669.859
                                - 100                                         
Covariance Type:                  opg                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
intercept    2.02e+04    107.648    187.608      0.000       2e+04    2.04e+04
Base_Price -1028.8910    107.147     -9.603      0.000   -1238.896    -818.886
Radio        103.0776    116.071      0.888      0.375    -124.418     330.573
InStore      476.2087    106.440      4.474      0.000     267.591     684.827
TV           315.7709     93.470      3.378      0.001     132.574     498.968
sigma2      8.659e+05   1.15e+05      7.513      0.000     6.4e+05    1.09e+06
===================================================================================
Ljung-Box (L1) (Q):                  31.29   Jarque-Bera (JB):                 3.10
Prob(Q):                              0.00   Prob(JB):                         0.21
Heteroskedasticity (H):               1.77   Skew:                            -0.33
Prob(H) (two-sided):                  0.10   Kurtosis:                         3.55
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
"""

#### Predictions (for next two time periods):

In [40]:
base_price = [15.64, 15.49]
radio = [279, 259]
instore = [41.50, 20.40]
tv = [103.44, 128.40]

testdf = pd.DataFrame({'Base_Price': base_price,'Radio': radio,'InStore': instore,'TV': tv})
 
mean = mktmix[['Base_Price','Radio','InStore','TV']].mean()
sd = mktmix[['Base_Price','Radio','InStore','TV']].std()

x = testdf[['Base_Price','Radio','InStore','TV']]
x_var= (x - mean)/sd
pd.options.display.float_format = '{:.3f}'.format
print(x_var)

   Base_Price  Radio  InStore     TV
0       0.680  0.256    0.659 -0.846
1       0.394  0.027   -0.884 -0.273
